### ISSUE TITLE
Support summary file (mdbook-toc)

### ISSUE THREAD

**Issue by jeffersonroth** [jeffersonroth/mdbook-reference-table#6]
Option 1: make it possible to use `mdbook-reference-table` in the summary file when using `mdbook-toc`.

Option 2: use the summary file as the source of truth for `reference-table.yaml`:
The command ```mdbook-reference-table update``` should validate and update the `reference-table.yaml` file.

```toml
# Book.toml

[preprocessor.reference-table]
 reference-table = "./reference-table.yaml"
 summary-file=".summary.md"
```

```markdown
# Summary

[Summary](./summary.md)

- [Audita quot](./content/subject-1/audita-quot.md)<!-- id:audita-quot -->
- [Aliter facta cornibus tandem](./content/subject-1/aliter-facta-cornibus-tandem.md)<!-- id:aliter-facta-cornibus-tandem -->
- [Bos quae inde limen](./content/subject-2/subfolder-1/bos-quae-inde-limen.md)<!-- id:bos-quae-inde-limen -->
- [Esse corpora Achaidas sacros ad quas](./content/subject-3/subfolder-1/subsubfolder-1/esse-corpora-achaidas-sacros-ad-quas.md)<!-- id:esse-corpora-achaidas-sacros-ad-quas -->
```

```yaml
# reference-table.yaml
reference-table:
  - id: "audita-quot"
    path: "content/subject-1/audita-quot.md"
  - id: "aliter-facta-cornibus-tandem"
    path: "content/subject-1/aliter-facta-cornibus-tandem.md"
  - id: "bos-quae-inde-limen"
    path: "content/subject-2/subfolder-1/bos-quae-inde-limen.md"
  - id: "esse-corpora-achaidas-sacros-ad-quas"
    path: "content/subject-3/subfolder-1/subsubfolder-1/esse-corpora-achaidas-sacros-ad-quas.md"
```

Option 3: don't use `reference-table.yaml`, use the summary file instead:
```toml
# Book.toml

[preprocessor.reference-table]
 reference-table = "./reference-table.yaml"
 summary-file=".summary.md"
```

```markdown
# Summary

[Summary](./summary.md)

- [Audita quot](./content/subject-1/audita-quot.md)<!-- id:audita-quot -->
- [Aliter facta cornibus tandem](./content/subject-1/aliter-facta-cornibus-tandem.md)<!-- id:aliter-facta-cornibus-tandem -->
- [Bos quae inde limen](./content/subject-2/subfolder-1/bos-quae-inde-limen.md)<!-- id:bos-quae-inde-limen -->
- [Esse corpora Achaidas sacros ad quas](./content/subject-3/subfolder-1/subsubfolder-1/esse-corpora-achaidas-sacros-ad-quas.md)<!-- id:esse-corpora-achaidas-sacros-ad-quas -->
```
